import { CatalogueItem } from "./catalogue-item";

export const testData: CatalogueItem[] = [
    {
        name: "Beef",
        ingredientSource: "Animal",
        flavourDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        baseEffectDescription: "Max HP +3" ,
        baseDc: 10,
        boostEffectDescription: "Healing received +1",
        boostDc: 2,
        marketPrice: 20,
        categoryTag: "Meat",
        effectTags: ["Health"],
        location: "The Cow Farm LMAO",
        imageUrl: "https://cdn.britannica.com/68/143268-050-917048EA/Beef-loin.jpg",
        rarity: 1
    },
    {
        name: "Pork",
        ingredientSource: "Animal",
        flavourDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        baseEffectDescription: "Temp HP +5",
        baseDc: 10,
        boostEffectDescription: "Breaks the oath of Islam",
        boostDc: 2,
        marketPrice: 40,
        categoryTag: "Meat",
        effectTags: ["Temporary Health", "RP"],
        location: "Pig farm",
        imageUrl: "https://omnivorescookbook.com/wp-content/uploads/2022/09/220908_Air-Fryer-Char-Siu-Pork_550-500x500.jpg",
        rarity: 2
    },
    {
        name: "Blue Fish",
        ingredientSource: "Animal",
        flavourDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        baseEffectDescription: "Breathe underwater",
        baseDc: 15,
        boostEffectDescription: "+5 Smelliness",
        boostDc: 5,
        marketPrice: 30,
        categoryTag: "Fish",
        effectTags: ["Sense", "Exploration"],
        location: "The Sea" ,
        imageUrl: "https://www.thesprucepets.com/thmb/Jg5byuBdix-TXtyLk4Xn575K3GE=/6078x0/filters:no_upscale():strip_icc()/low-maintenance-freshwater-fish-4770223-hero-ffb66c229c194e2db4916e88bbd17a15.jpg",
        rarity: 3
    },
    {
        name: "White Fish",
        ingredientSource: "Fish",
        flavourDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget est lorem ipsum dolor. Sed tempus urna et pharetra pharetra massa massa ultricies.",
        baseEffectDescription: "Advantage on persuasion checks",
        baseDc: 16,
        boostEffectDescription: "+2 to CHA",
        boostDc: 4,
        marketPrice: 50,
        categoryTag: "Fish",
        effectTags: ["Social", "Skill", "Ability Score", "Charisma", "Health"],
        location: "The Sea",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfHlcmASZgNOAA0mtIwob78oSLwGP1PybjDQ&s",
        rarity: 3
    },
    {
        name: "Fruit",
        ingredientSource: "Plant",
        flavourDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vestibulum mattis ullamcorper velit sed.",
        baseEffectDescription: "Support LGBTQIA+ rights for the rest of the day.",
        baseDc: 12,
        boostEffectDescription: "+12 Gayge.",
        boostDc: 6,
        marketPrice: 100,
        categoryTag: "Vegetable",
        effectTags: ["Personality Affecting", "Social"],
        location: "The Forest",
        imageUrl: "https://hillfresh.eu/wp-content/uploads/2021/12/aardbei-621x420.jpg",
        rarity: 3
    },
    {
        name: "Mushroom",
        ingredientSource: "Plant",
        flavourDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor.",
        baseEffectDescription: "Cast pass without trace once before rest.",
        baseDc: 20,
        boostEffectDescription: "Double numerical value of Base.",
        boostDc: 10,
        marketPrice: 200,
        categoryTag: "Vegetable",
        effectTags: ["Spell"],
        location: "Da Cave",
        imageUrl: "https://images.immediate.co.uk/production/volatile/sites/30/2023/08/Chestnut-mushrooms-a223a78.jpg?quality=90&resize=440,400",
        rarity: 4
    }
]